import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import dynamic from 'next/dynamic';
import styles from '../styles/Home.module.scss';

import useStore from 'shell/store';
const Counter = dynamic(() => import('shell/Counter'), { ssr: false });
// import useStore from '../lib/store';
// import Counter from '../components/Counter'

const Shell = () => {

  const { count, increment, decrement } = useStore();

  return (
    <div className={styles.container}>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Home Page (Shell)
        </h1>
        <Counter count={count} onIncrement={increment} onDecrement={decrement} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

Shell.getInitialProps = async () => {
  return {};
}

export default Shell
