import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.scss';
import dynamic from 'next/dynamic';

import useStore from 'shell/store';
const Counter = dynamic(() => import('shell/Counter'), {ssr: false});

const PDP = () => {
  const {count, increment, decrement} = useStore();
  return (
    <div className={styles.container}>
      <Head>
        <title>PDP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          PDP
        </h1>
        <Counter count={count} onIncrement={increment} onDecrement={decrement} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

PDP.getInitialProps = async () => {
  return {};
}

export default PDP
